#!/usr/bin/perl
# OpenPOWER Automated Test Project
#
# Contributors Listed Below - COPYRIGHT 2016
# [+] International Business Machines Corp.
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.

# Checks the layout of a machines.xml file.

# Author: Stewart Smith

use strict;

use XML::LibXML;
use Getopt::Long;

my $usage = "Syntax-check and list major elements in a OpenPower machines XML file.

Syntax: list-machines [OPTIONS] filename.xml

Where OPTIONS is zero or more of:
   --help : Display this message
\n";

my $schema_filename = "op-machines.xsd";

sub syntax()
{
    print "$usage";
    exit(1);
}

my $help = 0;
my $xmlfile_arg;

GetOptions("help|h|?" => \$help,
	   "<>" => sub { $xmlfile_arg = shift }
    ) or syntax();

syntax() if $help;

if ($xmlfile_arg eq "")
{
    print STDERR "ERROR: you must specify an XML file to test\n";
    exit(1);
}

my $parser = XML::LibXML->new();
my $dom = XML::LibXML->load_xml(location => $xmlfile_arg);
$parser->process_xincludes($dom);

# Validate the resulting XML
my $xmlschema = XML::LibXML::Schema->new(location => $schema_filename);
my $valid = eval { $xmlschema->validate($dom) };
die if $valid ne 0;
my $xmldata = $parser->parse_file($xmlfile_arg);

my @machines = $xmldata->findnodes('/machines/machine');
foreach my $machine (@machines)
{
    my $name = ($machine->findnodes('./name'))->to_literal;
    print $name."\n";
}
